import type { Metadata, Viewport } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import { Fraunces } from 'next/font/google';
import { ConsentedSpeedInsights } from '@/components/marketing/ConsentedSpeedInsights';

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
  display: 'swap',
  axes: ['SOFT', 'WONK', 'opsz'],
});
import './globals.css';
import { site } from '@/lib/site';
import { getTheme, themeToCss } from '@/lib/theme';
import { THEME_NO_FLASH_SCRIPT } from '@/lib/admin-theme';

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: `${site.name} — ${site.tagline} | Islington, London`,
    template: `%s | ${site.name} London`,
  },
  description: site.description,
  applicationName: site.name,
  authors: [{ name: site.name }],
  creator: site.name,
  publisher: site.name,
  formatDetection: { telephone: true, address: true, email: true },
  category: 'Health & Beauty',
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
  // apple-touch-icon is generated by app/apple-icon.tsx (file convention).
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
  },
  manifest: '/manifest.webmanifest',
  // Search-engine ownership verification (Search Console / Bing / Yandex).
  // Set the env vars in production to claim the property; absent → omitted.
  verification: {
    ...(process.env.GOOGLE_SITE_VERIFICATION ? { google: process.env.GOOGLE_SITE_VERIFICATION } : {}),
    ...(process.env.YANDEX_VERIFICATION ? { yandex: process.env.YANDEX_VERIFICATION } : {}),
    ...(process.env.BING_SITE_VERIFICATION ? { other: { 'msvalidate.01': process.env.BING_SITE_VERIFICATION } } : {}),
  },
};

export const viewport: Viewport = {
  themeColor: '#2a2420',
  colorScheme: 'light',
  width: 'device-width',
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Palette is injected as CSS variables here so a colour change in theme.ts
  // re-skins the entire site. getTheme() is synchronous (no I/O), so the
  // root layout can be static and ISR pages qualify for static optimisation.
  const theme = getTheme();
  return (
    <html lang="en-GB" className={`${GeistSans.variable} ${GeistMono.variable} ${fraunces.variable}`}>
      <head>
        {/* WordPress-editable brand palette → CSS variable overrides. */}
        <style id="brand-theme" dangerouslySetInnerHTML={{ __html: themeToCss(theme) }} />
        {/* Admin dark/system mode: resolve before paint, /admin only (no flash,
            no leak onto the public site). See lib/admin-theme.ts. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_NO_FLASH_SCRIPT }} />
        {/* Fallback: ensure scroll-revealed content is visible without JS. */}
        <noscript>
          <style>{`[style*="opacity:0"]{opacity:1!important;transform:none!important;filter:none!important}`}</style>
        </noscript>
      </head>
      <body>{children}<ConsentedSpeedInsights /></body>
    </html>
  );
}
