// GENERATED from docs/finance/model-inputs.json by docs/finance/gen_admin_defaults.py — do not edit by hand.
// Seed values for the admin Finance planner. Sources and confidence notes live in
// docs/finance/model-inputs.json (every figure carries a basis) and docs/finance/README.md.

import type { PlannerInputs } from '@/lib/finance-planner-types';

export const PLANNER_DEFAULTS: PlannerInputs = {
  "startMonth": "2026-09",
  "months": 36,
  "rooms": 9,
  "hvacRooms": 9,
  "openDaysPerWeek": 6,
  "openHoursPerDay": 9.5,
  "staff": {
    "practitionerSalary": 41000,
    "receptionistSalary": 27000,
    "ownerSalary": 48000,
    "onCost": 1.16,
    "practitionersByYear": [
      2,
      3,
      5
    ],
    "receptionistsByYear": [
      1,
      1,
      2
    ],
    "productiveHoursPerWeek": 30,
    "workingWeeks": 46
  },
  "energy": {
    "unitRatePence": 27,
    "standingPencePerDay": 55,
    "baseLoadKWhPerDay": 12,
    "hvacKWhPerRoomMonth": [
      82,
      80,
      68,
      36,
      45,
      120,
      180,
      180,
      45,
      36,
      68,
      82
    ]
  },
  "property": {
    "rent": 64000,
    "rates": 11500,
    "serviceCharge": 0
  },
  "overheads": {
    "insurance": 1500,
    "softwareMonthly": 50,
    "cardFeePct": 0.017,
    "cardShare": 0.95,
    "cleaningMonthly": 400,
    "otherMonthly": 200
  },
  "marketing": {
    "pctByYear": [
      0.12,
      0.1,
      0.08
    ],
    "floorMonthly": 1500
  },
  "tax": {
    "vatRate": 0.2,
    "vatThreshold": 90000,
    "priorTurnover": 25000,
    "vatOverrideMonth": 0,
    "ctSmallRate": 0.19,
    "ctSmallLimit": 50000,
    "ctMarginalRate": 0.265,
    "ctMarginalLimit": 250000,
    "ctMainRate": 0.25
  },
  "machines": [
    {
      "key": "diode-laser",
      "name": "Diode laser hair-removal platform",
      "ownership": "OWNED (serves 63% of recent non-consultation bookings)",
      "purchase": 18000,
      "inServiceMonth": 0,
      "lifeYears": 7,
      "kwhPerTreatmentHour": 1,
      "annualService": 1800,
      "plannedHoursMonth": 250,
      "consumablesNote": "£1–£3.50/session gel + razors (scaled by area in treatments table); handpiece stack rated 1M+ shots, replacement is a maintenance event not a per-session cost",
      "basis": "UK trade listings (thelasermachineco, britishlasers): clinic-grade £8k–£15k, premium £30k–£60k; typical premium-clinic buy £18k–£35k. Service ~10% of typical price per britishlasers contract range £1k–£3.5k. kWh: plate 2–3.5 kW at 25–40% duty (engineering estimate)."
    },
    {
      "key": "laser-ipl-platform",
      "name": "Multi-application laser/IPL skin platform (shared 'laser' resource pool; may be same combi chassis as diode — Lynton Lumina class covers both for £30k–£50k)",
      "ownership": "OWNED (pigmentation/vascular/IPL/rejuvenation/resurfacing/rosacea/wrinkle/spider-vein/carbon-peel/fungal-nail all book against it)",
      "purchase": 45000,
      "inServiceMonth": 0,
      "lifeYears": 8,
      "kwhPerTreatmentHour": 0.8,
      "annualService": 3000,
      "plannedHoursMonth": 30,
      "consumablesNote": "£2/session gel; £5–£7 carbon lotion for Hollywood Peel; IPL flashlamp refurb £500–£1,500 per handpiece every ~50k–100k pulses (treat as maintenance)",
      "basis": "Lumenis Stellar M22 £45k–£70k; Lynton Lumina £28k–£50k. Service £2k–£5k/yr (Lynton/Lumenis UK contracts, 6–8% of price). Duty 25–35% of plate 1.5–3 kW."
    },
    {
      "key": "pico-laser-PLANNED",
      "name": "Q-switched/picosecond tattoo & pigment laser",
      "ownership": "NOT YET PURCHASED — phase-2 capex; tattoo/PMU pages live with prices, bookings closed",
      "purchase": 110000,
      "inServiceMonth": null,
      "lifeYears": 8,
      "kwhPerTreatmentHour": 1,
      "annualService": 7500,
      "plannedHoursMonth": 25,
      "consumablesNote": "~£1–£2.50/session (gel, wipes, aftercare dressings) — negligible; service contract is the real running cost (8–10% of purchase)",
      "basis": "PicoSure Pro/PicoWay £90k–£175k; mid-tier Quanta/Lutronic £50k–£80k; Far-East pico £12.5k; Q-switched Nd:YAG alternative £15k–£40k. Model as a capex decision with three price scenarios — £110k premium figure only holds if buying PicoSure-class."
    },
    {
      "key": "co2-laser",
      "name": "Fractional CO2 laser with intimate/gynae handpiece",
      "ownership": "VERIFY — intimate line is COMING_SOON; codebase confirms the treatment tech but not that the unit is on site",
      "purchase": 55000,
      "inServiceMonth": 0,
      "lifeYears": 9,
      "kwhPerTreatmentHour": 0.4,
      "annualService": 4000,
      "plannedHoursMonth": 8,
      "consumablesNote": "£20–£80/session single-use gynae probe covers/hygiene sleeves + numbing cream (£50 midpoint used in treatments table)",
      "basis": "Deka SmartXide/Alma FemiLift £40k–£90k with intimate handpiece; generic £5k–£15k; premium-clinic buy £45k–£65k. RF-excited tubes last 8–12 yrs. Service 6–8% of purchase."
    },
    {
      "key": "hifu",
      "name": "HIFU (SMAS ultrasound) with face + body cartridges",
      "ownership": "OWNED (live bookings)",
      "purchase": 30000,
      "inServiceMonth": 0,
      "lifeYears": 6,
      "kwhPerTreatmentHour": 0.3,
      "annualService": 2250,
      "plannedHoursMonth": 25,
      "consumablesNote": "SHOT-LIMITED CARTRIDGES — the largest device consumable line: £30–£100/session Ultraformer-class (£40 small area / £65 full face / £80 body used in treatments table); would be £300–£900/session if Ultherapy transducers. Plus gel.",
      "basis": "Classys Ultraformer III/MPT £25k–£40k UK; Ultherapy £30k–£60k; generic 7D £3k–£8k. Cartridges ~10k–20k shots at £300–£600 each. Service £1.5k–£3k/yr. Duty 30–40% of 0.5–1 kW plate."
    },
    {
      "key": "rf-tightening",
      "name": "Radiofrequency skin-tightening device",
      "ownership": "OWNED (live bookings under rf-lifting/rf-skin-tightening)",
      "purchase": 40000,
      "inServiceMonth": 0,
      "lifeYears": 7,
      "kwhPerTreatmentHour": 0.5,
      "annualService": 3000,
      "plannedHoursMonth": 12,
      "consumablesNote": "£2–£5/session conductive gel (plain RF — catalogue has no RF-microneedling, so no Morpheus8-style £100–£180 tips)",
      "basis": "BTL Exilis Ultra £30k–£45k; mid-tier £5k–£15k; premium tier £30k–£50k. Service 5–8% of purchase. Near-continuous RF delivery, duty 40–60%."
    },
    {
      "key": "hydrafacial-platform",
      "name": "HydraFacial-style vortex facial platform",
      "ownership": "OWNED (live bookings)",
      "purchase": 25000,
      "inServiceMonth": 0,
      "lifeYears": 6,
      "kwhPerTreatmentHour": 0.2,
      "annualService": 1500,
      "plannedHoursMonth": 60,
      "consumablesNote": "£15–£25/session tips + branded serums, scaling with tier (Signature £15 / Deluxe £20 / Platinum £25); genuine HydraFacial ties serum purchase to warranty. Deep Cleansing menu on same platform at £8–£15/session products.",
      "basis": "Genuine HydraFacial Syndeo/Elite £20k–£32k UK; clones £3k–£8k. Consumables $20–$30/treatment (konmison/workee)."
    },
    {
      "key": "endosphere-vacuum",
      "name": "Endosphere compressive micro-vibration + anti-cellulite vacuum body platform",
      "ownership": "OWNED (body-contouring + vacuum-massage bookings)",
      "purchase": 27000,
      "inServiceMonth": 0,
      "lifeYears": 7,
      "kwhPerTreatmentHour": 0.35,
      "annualService": 1750,
      "plannedHoursMonth": 45,
      "consumablesNote": "£1–£3/session oil/cream/disposable bodysuits",
      "basis": "Endospheres AK Body dealer pricing ~€25k–€35k (~£21k–£30k, baltic-lasers.eu) — DEALER-QUOTE ESTIMATE, not published list price. Service/roller refurb ~5% of price. Motor runs near-continuously at 0.3–0.5 kW."
    },
    {
      "key": "microneedling-pen",
      "name": "Microneedling pen (+ BB Glow micro-channelling)",
      "ownership": "OWNED (live bookings)",
      "purchase": 3000,
      "inServiceMonth": 0,
      "lifeYears": 4,
      "kwhPerTreatmentHour": 0.02,
      "annualService": 100,
      "plannedHoursMonth": 18,
      "consumablesNote": "£5–£35/session sterile needle cartridge + serum (SkinPen cartridges £25–£35, generic £5–£20); BB Glow tinted ampoule £5–£15 extra",
      "basis": "SkinPen Precision £2k–£3.5k, Dermapen 4 £3k–£5.5k. Negligible power. Battery/handpiece wear limits life to 3–5 yrs."
    },
    {
      "key": "microdermabrasion",
      "name": "Microdermabrasion device (diamond-tip/crystal)",
      "ownership": "OWNED (1 booking in 90d)",
      "purchase": 3000,
      "inServiceMonth": 0,
      "lifeYears": 6,
      "kwhPerTreatmentHour": 0.25,
      "annualService": 300,
      "plannedHoursMonth": 8,
      "consumablesNote": "£1–£3/session filters + disposable tips (crystals £3–£5 if crystal type)",
      "basis": "UK professional diamond-tip units £1.2k–£6k, typical £2.5k–£3.5k. Vacuum pump 0.2–0.4 kW near-continuous."
    },
    {
      "key": "microcurrent-led",
      "name": "Microcurrent facial toning device + LED panel",
      "ownership": "AMBIGUOUS — codebase marks microcurrent/LED 'onRequest, machine not yet in', but the live catalogue lists Microcurrent lifting and LED as NORMAL and there are 6 microcurrent-facial bookings in 90d. Assume a non-CACI-branded unit is on site; confirm with owner.",
      "purchase": 15000,
      "inServiceMonth": 0,
      "lifeYears": 8,
      "kwhPerTreatmentHour": 0.1,
      "annualService": 750,
      "plannedHoursMonth": 25,
      "consumablesNote": "£2–£5/session conductive gel, cotton buds; hydra mask +£5; LED session ~£1",
      "basis": "CACI Synergy £14k–£17k inc training, Ultimate £18k–£22k, Classic £9k–£12k (dealer channel, prices on application). If the on-site unit is a generic microcurrent+LED device the capex could be £2k–£5k — use the low end unless CACI-branded purchase is confirmed."
    },
    {
      "key": "none-injectables",
      "name": "Injectables room (no machine): electric couch + MHRA-compliant medical fridge + sharps/emergency kit",
      "ownership": "OWNED",
      "purchase": 2500,
      "inServiceMonth": 0,
      "lifeYears": 10,
      "kwhPerTreatmentHour": 0,
      "annualService": 150,
      "plannedHoursMonth": 25,
      "consumablesNote": "DOMINANT COGS LINE: toxin vials £45–£85/tx by area count, HA filler £35–£85/tx by ml, fat-dissolving vials £35–£75/tx, polynucleotides £70–£100/tx, meso cocktails £25/tx, plus needles/cannulae/numbing (in per-row figures). Fridge runs 24/7: ~1.5–3 kWh/day counted in base load, not per-treatment.",
      "basis": "Couch £700–£2,500, pharmacy fridge £400–£1,500, kit £200–£500. Injectable COGS from UK aesthetic wholesale norms (Church Pharmacy tier) — brand-dependent estimates, no recorded costs."
    },
    {
      "key": "none-manual",
      "name": "Topical/manual treatment room kit (couch, trolley, steamer, hot cabinet)",
      "ownership": "OWNED",
      "purchase": 1500,
      "inServiceMonth": 0,
      "lifeYears": 9,
      "kwhPerTreatmentHour": 0.1,
      "annualService": 100,
      "plannedHoursMonth": 25,
      "consumablesNote": "£1.50–£15/session: peel solutions + neutralisers £10–£15, massage oils £2–£4, masks/towels/products £3–£8",
      "basis": "UK salon equipment norms; steamer ~0.3 kW only while on."
    }
  ],
  "enhancements": [
    {
      "name": "Initial fit-out / leasehold improvements",
      "cost": 0,
      "inServiceMonth": 0,
      "lifeYears": 10
    },
    {
      "name": "Example — reception refresh (edit or zero out)",
      "cost": 8000,
      "inServiceMonth": 6,
      "lifeYears": 5
    }
  ],
  "pricing": {
    "targetMarginByClass": {
      "diode-laser": 0.7,
      "laser-ipl-platform": 0.7,
      "pico-laser-PLANNED": 0.7,
      "co2-laser": 0.7,
      "hifu": 0.6,
      "rf-tightening": 0.7,
      "hydrafacial-platform": 0.65,
      "endosphere-vacuum": 0.7,
      "microneedling-pen": 0.65,
      "microdermabrasion": 0.7,
      "microcurrent-led": 0.7,
      "none-injectables": 0.55,
      "none-manual": 0.65
    },
    "roundTo": 1,
    "priceForVat": true,
    "courseDiscounts": {
      "s3": 0.1,
      "s6": 0.15,
      "s10": 0.2
    }
  },
  "volumes": {
    "utilisation": [
      0.04,
      0.046,
      0.052000000000000005,
      0.057999999999999996,
      0.064,
      0.07,
      0.076,
      0.08199999999999999,
      0.08800000000000001,
      0.094,
      0.1,
      0.106,
      0.11199999999999999,
      0.11800000000000001,
      0.124,
      0.13,
      0.136,
      0.142,
      0.14800000000000002,
      0.154,
      0.16,
      0.166,
      0.172,
      0.17800000000000002,
      0.184,
      0.19,
      0.196,
      0.20199999999999999,
      0.20800000000000002,
      0.214,
      0.22,
      0.226,
      0.23199999999999998,
      0.23800000000000002,
      0.244,
      0.25
    ],
    "mixByClass": {
      "diode-laser": 49.5,
      "laser-ipl-platform": 3.0,
      "hifu": 2.0,
      "rf-tightening": 2.0,
      "hydrafacial-platform": 11.0,
      "endosphere-vacuum": 8.0,
      "microneedling-pen": 3.0,
      "microdermabrasion": 0.5,
      "microcurrent-led": 4.0,
      "none-injectables": 3.0,
      "none-manual": 2.0,
      "co2-laser": 0.0,
      "pico-laser-PLANNED": 0.0,
      "consultation": 12.0
    },
    "avgPriceOverride": {},
    "avgDurationOverride": {}
  }
};

/** treatment service slug -> machine class (drives energy/service/depreciation per session). */
export const CLASS_BY_SERVICE_SLUG: Record<string, string> = {
  "lhr-women": "diode-laser",
  "lhr-men": "diode-laser",
  "intimate-rejuvenation": "co2-laser",
  "laser-pigmentation": "laser-ipl-platform",
  "vascular-lesions": "laser-ipl-platform",
  "spider-veins": "laser-ipl-platform",
  "carbon-laser-peel": "laser-ipl-platform",
  "fungal-nail": "laser-ipl-platform",
  "laser-tattoo-removal": "pico-laser-PLANNED",
  "pmu-removal": "pico-laser-PLANNED",
  "hydrafacial": "hydrafacial-platform",
  "smas-hifu": "hifu",
  "cosmetic-peels": "none-manual",
  "fat-dissolving": "none-injectables",
  "rf-lifting": "rf-tightening",
  "ipl-phototherapy": "laser-ipl-platform",
  "laser-skin-rejuvenation": "laser-ipl-platform",
  "laser-skin-resurfacing": "laser-ipl-platform",
  "endosphere": "endosphere-vacuum",
  "caci": "microcurrent-led",
  "red-carpet-lift": "microneedling-pen",
  "bb-glow-r3q4": "microneedling-pen",
  "massage-yuli": "none-manual",
  "microneedling-oosw": "microneedling-pen",
  "vacuum-massage-68b9": "endosphere-vacuum",
  "deep-cleansing-8y6d": "hydrafacial-platform",
  "led-light-therapy-9h76": "microcurrent-led",
  "face-head-massage-ax9e": "none-manual",
  "microdermabrasion-epd8": "microdermabrasion",
  "microcurrent-lifting-fm2d": "microcurrent-led",
  "botox-j2j7": "none-injectables",
  "botox-r9w5": "none-injectables",
  "lip-filler-k4wd": "none-injectables",
  "mesotherapy-mfc8": "none-injectables",
  "polynucleotides-n29n": "none-injectables",
  "rosacea-treatment-ojdv": "laser-ipl-platform",
  "laser-wrinkles-removal-oyti": "laser-ipl-platform"
};

/** Estimated consumables £/session keyed "serviceSlug|variantName" (no recorded COGS exist in the DB). */
export const CONSUMABLES_BY_VARIANT: Record<string, number> = {
  "lhr-women|Bikini Line": 1.5,
  "lhr-women|Brazilian": 1.5,
  "lhr-women|Hollywood Brazilian (incl. Peri-Anal)": 1.5,
  "lhr-women|Behind (Peri-Anal)": 1.5,
  "lhr-women|Brazilian/Bikini & Underarms": 1.5,
  "lhr-women|Hollywood Brazilian (incl. Peri-Anal) & Underarms": 1.5,
  "lhr-women|Hollywood Brazilian (incl. Peri-Anal) & Full Legs": 2,
  "lhr-women|Full Leg & Underarms": 2,
  "lhr-women|Lower Leg, Brazilian/Bikini & Underarms": 2,
  "lhr-women|Full Legs, Brazilian/Bikini & Underarms": 2,
  "lhr-women|Full Legs, Hollywood Brazilian (incl. Peri-Anal) & Underarms": 2,
  "lhr-women|Eyebrows (middle, above bridge of nose)": 1,
  "lhr-women|Lip": 1,
  "lhr-women|Chin": 1,
  "lhr-women|Sides of Face": 1.5,
  "lhr-women|Lip & Chin": 1.5,
  "lhr-women|Jawline & Chin": 1.5,
  "lhr-women|½ Face (forehead–nose or upper lip–chin)": 1.5,
  "lhr-women|Front of Neck": 1.5,
  "lhr-women|Back of Neck": 1.5,
  "lhr-women|Full Face": 1.5,
  "lhr-women|Full Face & Neck": 1.5,
  "lhr-women|Underarms": 1,
  "lhr-women|Snail Trail / Naval": 1.5,
  "lhr-women|Stomach": 1.5,
  "lhr-women|Shoulders": 1.5,
  "lhr-women|½ Arms": 1.5,
  "lhr-women|Chest": 1.5,
  "lhr-women|Chest & Stomach": 2,
  "lhr-women|Full Arms": 2,
  "lhr-women|Fingers & Toes": 1,
  "lhr-women|Feet & Toes": 1,
  "lhr-women|Buttocks": 1.5,
  "lhr-women|Half Body": 2.5,
  "lhr-women|Lower Leg": 1.5,
  "lhr-women|Full Legs": 2,
  "lhr-women|Full Body": 3,
  "lhr-men|Centre Brow": 1,
  "lhr-men|Front of Neck": 1.5,
  "lhr-men|Back of Neck": 1.5,
  "lhr-men|Full Beard": 1.5,
  "lhr-men|Full Beard & Neck": 2,
  "lhr-men|Underarms": 1.5,
  "lhr-men|½ Arms": 1.5,
  "lhr-men|Shoulders": 1.5,
  "lhr-men|Lower Back": 1.5,
  "lhr-men|Full Arms": 2,
  "lhr-men|Chest": 1.5,
  "lhr-men|Stomach": 1.5,
  "lhr-men|Chest & Stomach": 2,
  "lhr-men|Full Back": 2,
  "lhr-men|Full Back & Shoulders": 2.5,
  "lhr-men|Full Back, Shoulders, Chest & Stomach": 3,
  "lhr-men|Full Body (excl. face)": 3.5,
  "lhr-men|Feet & Toes": 1,
  "lhr-men|Buttocks": 1.5,
  "lhr-men|Male Brazilian": 1.5,
  "lhr-men|Lower Legs": 2,
  "lhr-men|Any Male Bikini (incl. Peri-Anal)": 1.5,
  "lhr-men|Full Legs": 2.5,
  "intimate-rejuvenation|CO2 Laser Rejuvenation": 50,
  "intimate-rejuvenation|Intimate Area Whitening": 50,
  "laser-pigmentation|Face": 2,
  "vascular-lesions|Face": 2,
  "spider-veins|Nose Thread Vein": 2,
  "spider-veins|Cheek Thread Vein": 2,
  "spider-veins|Leg Thread Vein": 3,
  "carbon-laser-peel|Neck": 5,
  "carbon-laser-peel|Full Face": 5,
  "carbon-laser-peel|Face & Neck": 6,
  "carbon-laser-peel|Face, Neck & Décolleté": 7,
  "fungal-nail|1 Foot": 2,
  "fungal-nail|2 Feet": 2,
  "laser-tattoo-removal|Very Small (1–3 cm)": 1,
  "laser-tattoo-removal|Small (4–6 cm)": 1,
  "laser-tattoo-removal|Medium (7–15 cm)": 1.5,
  "laser-tattoo-removal|Large (16–20 cm)": 2,
  "laser-tattoo-removal|X-Large (21 cm+)": 2.5,
  "pmu-removal|Eyebrows": 1,
  "hydrafacial|Signature Express (30 min)": 15,
  "hydrafacial|Full Face Deluxe (50 min)": 20,
  "hydrafacial|Platinum — Anti-Acne (60 min)": 25,
  "hydrafacial|Platinum — Collagen (60 min)": 25,
  "hydrafacial|Platinum — Pigmentation & Sun Damage (60 min)": 25,
  "hydrafacial|Platinum — Anti-Ageing (60 min)": 25,
  "hydrafacial|Platinum — Brightening (60 min)": 25,
  "smas-hifu|Eyebrow Lift": 40,
  "smas-hifu|Forehead Lift": 40,
  "smas-hifu|Neck Lift": 50,
  "smas-hifu|Jawline Lift": 50,
  "smas-hifu|Full Face": 65,
  "smas-hifu|Full Face & Neck": 75,
  "smas-hifu|Stomach": 80,
  "smas-hifu|Outer Thighs": 80,
  "smas-hifu|Inner Thighs": 80,
  "smas-hifu|Back & Flanks": 80,
  "smas-hifu|Buttock": 80,
  "smas-hifu|Skin Above the Knee Caps": 50,
  "smas-hifu|Arms (bingo wings)": 65,
  "cosmetic-peels|Full Face": 12,
  "fat-dissolving|Small Area (under chin)": 35,
  "fat-dissolving|Medium Area (Stomach, Bingo Wings, Knees)": 55,
  "fat-dissolving|Large Area (Thighs, Waist, Stomach)": 75,
  "rf-lifting|RF Lifting": 3,
  "ipl-phototherapy|Face": 2,
  "ipl-phototherapy|Face & Neck": 2,
  "laser-skin-rejuvenation|Face & Neck": 2,
  "laser-skin-rejuvenation|Face": 2,
  "laser-skin-resurfacing|Laser Skin Resurfacing": 2,
  "endosphere|BodySphere 30 min": 2,
  "endosphere|BodySphere 45 min": 2,
  "endosphere|BodySphere 60 min": 2,
  "endosphere|BodySphere & Facial Massage 60 min": 2.5,
  "caci|CACI Face & Neck Lift": 4,
  "caci|CACI with Hydra Mask": 8,
  "caci|CACI Jaw Line Lift": 3,
  "caci|Microcurrent": 3,
  "red-carpet-lift|BB Glow": 25,
  "bb-glow-r3q4|BB Glow": 25,
  "massage-yuli|Deep Tissue Massage": 3,
  "massage-yuli|Swedish Massage": 3,
  "massage-yuli|Back, Neck & Shoulders Massage": 2,
  "massage-yuli|Relaxing Massage": 3,
  "massage-yuli|Hot Stone Massage": 4,
  "massage-yuli|Full Body Massage": 3,
  "massage-yuli|Lymphatic Drainage Massage": 3,
  "microneedling-oosw|Microneedling for face": 20,
  "microneedling-oosw|Microneedling for face and neck": 22,
  "microneedling-oosw|Microneedling with hyaluronic acid serum or exosome serum": 35,
  "vacuum-massage-68b9|Vacuum massage (30 min)": 2,
  "vacuum-massage-68b9|Vacuum massage (45 min)": 2,
  "vacuum-massage-68b9|Vacuum massage (60 min)": 2,
  "deep-cleansing-8y6d|Deep Cleansing Classic": 8,
  "deep-cleansing-8y6d|Deep Cleansing with LED Therapy": 10,
  "deep-cleansing-8y6d|Deep Cleansing with Alginate Mask": 12,
  "deep-cleansing-8y6d|Deep Cleansing with Peel": 15,
  "led-light-therapy-9h76|Facial LED Light Therapy": 1,
  "face-head-massage-ax9e|Head Massage": 2,
  "face-head-massage-ax9e|Face Massage 15 min": 1.5,
  "face-head-massage-ax9e|Face Massage 30 min": 2,
  "face-head-massage-ax9e|Indian Head Massage": 2,
  "microdermabrasion-epd8|Microdermabrasion": 2,
  "microcurrent-lifting-fm2d|Microcurrent lifting": 3,
  "microcurrent-lifting-fm2d|Microcurrent lifting face & neck lift": 3,
  "microcurrent-lifting-fm2d|Microcurrent lifting with hydra mask": 8,
  "botox-j2j7|Ladie's Anti-Wrinkle 1 area": 45,
  "botox-r9w5|Ladie's Anti-Wrinkle 1 area": 45,
  "botox-j2j7|Ladie's Anti-Wrinkle 2 area": 60,
  "botox-r9w5|Ladie's Anti-Wrinkle 2 area": 60,
  "botox-j2j7|Ladie's Anti-Wrinkle 3 area": 75,
  "botox-r9w5|Ladie's Anti-Wrinkle 3 area": 75,
  "botox-j2j7|Men's Anti-Wrinkle 1 area": 55,
  "botox-r9w5|Men's Anti-Wrinkle 1 area": 55,
  "botox-j2j7|Men's Anti-Wrinkle 2 area": 70,
  "botox-r9w5|Men's Anti-Wrinkle 2 area": 70,
  "botox-j2j7|Men's Anti-Wrinkle 3 area": 85,
  "botox-r9w5|Men's Anti-Wrinkle 3 area": 85,
  "lip-filler-k4wd|Lip Filler 0.5 ml": 35,
  "lip-filler-k4wd|Lip Filler 0.7 ml": 45,
  "lip-filler-k4wd|Lip Filler 1 ml": 60,
  "lip-filler-k4wd|Lip Filler 1.5 ml": 85,
  "mesotherapy-mfc8|Mesotherapy Under Eyes": 25,
  "mesotherapy-mfc8|Mesotherapy Full Face": 25,
  "mesotherapy-mfc8|Mesotherapy Decolletage": 25,
  "mesotherapy-mfc8|Mesotherapy Hair Growth": 25,
  "mesotherapy-mfc8|Mesotherapy Neck": 25,
  "polynucleotides-n29n|Polynucleotides Face": 70,
  "polynucleotides-n29n|Polynucleotides Eyes": 70,
  "polynucleotides-n29n|Polynucleotides Hair Rejuvenation": 70,
  "polynucleotides-n29n|Rejuran Healer - Advanced Polynucleotides": 100,
  "rosacea-treatment-ojdv|Rosacea Treatment Face": 2,
  "laser-wrinkles-removal-oyti|Laser Wrinkles Removal Face": 2
};

/** Fallback consumables £/session per machine class for variants with no per-variant estimate. */
export const CONSUMABLES_CLASS_FALLBACK: Record<string, number> = {
  "diode-laser": 1.5,
  "co2-laser": 50,
  "laser-ipl-platform": 2,
  "pico-laser-PLANNED": 1.5,
  "hydrafacial-platform": 20,
  "hifu": 65,
  "none-manual": 3,
  "none-injectables": 60,
  "rf-tightening": 3,
  "endosphere-vacuum": 2,
  "microcurrent-led": 3,
  "microneedling-pen": 25,
  "microdermabrasion": 2
};
