// AUTO-IMPORTED treatment pages from the existing kclinics.co.uk WordPress site.
// Copy extracted from the official WP export. Edit freely.
import type { Treatment } from "./treatments";

export const importedTreatments: Treatment[] = [
  {
    slug: "laser-skin-rejuvenation",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Laser Skin Rejuvenation",
    tagline: "Perfect for issues such as redness, acne and uneven skin tone.",
    metaTitle: "Laser Skin Rejuvenation in London (Islington) | K Clinics",
    metaDescription: "Laser skin rejuvenation is a modern, non-invasive procedure that uses high-energy light to improve the texture, tone and overall condition of the skin. The",
    keywords: ["Laser Skin Rejuvenation London","Laser Skin Rejuvenation Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "Laser skin rejuvenation is a modern, non-invasive procedure that uses high-energy light to improve the texture, tone and overall condition of the skin. The laser promotes collagen synthesis and natural regeneration processes by penetrating the skin's deep layers. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Hydration","text":"Delivered by certified specialists with years of experience."},{"title":"Fine Lines & Wrinkles","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Hyperpigmentation & Uneven Skin Tone","text":"Every treatment is tailored to your goals and your skin."},{"title":"Acne Scars","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Laser Skin Rejuvenation will I need?","a":"Typically 3-6 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"20-25 minutes per session"},{"label":"Sessions","value":"3-6 sessions with intervals "},{"label":"Consult","value":"Complimentary"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#a98a6d","#7b6a5d"],
  },
  {
    slug: "pigmentation-correction",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Pigmentation Correction",
    tagline: "Perfect for issues such as redness, acne and uneven skin tone.",
    metaTitle: "Pigmentation Correction in London (Islington) | K Clinics",
    metaDescription: "The pigmentation correction procedure uses high-intensity light or laser energy to break down excess pigment on the skin with a higher concentration of mel",
    keywords: ["Pigmentation Correction London","Pigmentation Correction Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "The pigmentation correction procedure uses high-intensity light or laser energy to break down excess pigment on the skin with a higher concentration of melanin. This heat from the conversion of light energy takes out extra pigment from skin without damaging the surrounding tissue. As a result, skin returns natural shine, balances the skin tone and promotes skin cell renewal. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Dullness & Dryness","text":"Delivered by certified specialists with years of experience."},{"title":"Hyperpigmentation","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Skin Sensitivity","text":"Every treatment is tailored to your goals and your skin."},{"title":"Texture & Tone","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Pigmentation Correction will I need?","a":"Typically 3-5 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"20-30 minutes per session"},{"label":"Sessions","value":"3-5 sessions with intervals "},{"label":"Results","value":"lasting up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#c2a589","#7b6a5d"],
  },
  {
    slug: "vascular-lesions-treatment",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Vascular Lesions Treatment",
    tagline: "Perfect for treating vascular lesions, such as rosacea, dilated capillaries, hemangiomas and spider veins.",
    metaTitle: "Vascular Lesions Treatment in London (Islington) | K Clinics",
    metaDescription: "The vascular lesions treatment uses high-intensity light or laser energy to target affected blood vessels. Heat is produced by the conversion of light ener",
    keywords: ["Vascular Lesions Treatment London","Vascular Lesions Treatment Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "The vascular lesions treatment uses high-intensity light or laser energy to target affected blood vessels. Heat is produced by the conversion of light energy, which causes dilated capillaries or blood vessels to coagulate (close) without causing damage to the surrounding tissues. As a result, the vessels are destroyed and the body naturally eliminates them, giving the skin its natural appearance, suppleness and even tone. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Dullness & Dryness","text":"Delivered by certified specialists with years of experience."},{"title":"Vascular Lesions","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Sensitive Skin","text":"Every treatment is tailored to your goals and your skin."},{"title":"Reduction of Redness","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Vascular Lesions Treatment will I need?","a":"Typically 3-5 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"20-30 minutes per session"},{"label":"Sessions","value":"3-5 sessions with intervals "},{"label":"Results","value":"Lasting up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#7b6a5d","#2a2420"],
  },
  {
    slug: "scar-stretch-mark-reduction",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Scar & Stretch Mark Reduction",
    tagline: "Perfect for issues such as redness, acne and uneven skin tone.",
    metaTitle: "Scar & Stretch Mark Reduction in London (Islington) | K Clinics",
    metaDescription: "The procedure uses laser energy or high-intensity light to deeply penetrate the skin. The light energy promotes the creation of collagen and elastin by sti",
    keywords: ["Scar & Stretch Mark Reduction London","Scar & Stretch Mark Reduction Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "The procedure uses laser energy or high-intensity light to deeply penetrate the skin. The light energy promotes the creation of collagen and elastin by stimulating the body's natural regeneration mechanisms. This improves skin tone overall, smoothes out the texture of the skin, and makes scars and stretch marks less noticeable. The skin gets smoother, firmer, and more uniformly coloured with each treatment. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Texture Improvement","text":"Delivered by certified specialists with years of experience."},{"title":"Reduction in Scars","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Stretch Mark Reduction","text":"Every treatment is tailored to your goals and your skin."},{"title":"Regeneration","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Scar & Stretch Mark Reduction will I need?","a":"Typically 3-6 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"20-30 minutes per session"},{"label":"Sessions","value":"3-6 sessions with intervals "},{"label":"Results","value":"Lasting up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#a98a6d","#4a3f37"],
  },
  {
    slug: "spider-veins-removal",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Spider Veins Removal",
    tagline: "Perfect for Removing Spider Veins and Improving Skin Tone.",
    metaTitle: "Spider Veins Removal in London (Islington) | K Clinics",
    metaDescription: "Tired of visible spider veins making your skin look uneven? Spider vein removal targets damaged blood veins with laser or light radiation. Heat is produced",
    keywords: ["Spider Veins Removal London","Spider Veins Removal Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "Tired of visible spider veins making your skin look uneven? Spider vein removal targets damaged blood veins with laser or light radiation. Heat is produced from the energy, closing the damaged veins without causing damage to the surrounding skin. Your skin in result looks smoother and more evenly toned as the body gradually gets rid of these veins on its own. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Redness","text":"Delivered by certified specialists with years of experience."},{"title":"Even Skin Tone","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Smooth Texture","text":"Every treatment is tailored to your goals and your skin."},{"title":"Minimised Vein Visibility","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Spider Veins Removal will I need?","a":"Typically lasting up to 12 months. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"20-30 minutes per session"},{"label":"Sessions","value":"lasting up to 12 months"},{"label":"Consult","value":"Complimentary"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#c2a589","#4a3f37"],
  },
  {
    slug: "laser-skin-resurfacing",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Laser Skin Resurfacing",
    tagline: "Perfect for restoring skin texture, reducing scars, stretch marks and fine lines.",
    metaTitle: "Laser Skin Resurfacing in London (Islington) | K Clinics",
    metaDescription: "Looking for a way to restore your skin’s smoothness and freshness? Laser skin resurfacing is an innovative technique that deeply penetrates the skin by las",
    keywords: ["Laser Skin Resurfacing London","Laser Skin Resurfacing Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "Looking for a way to restore your skin’s smoothness and freshness? Laser skin resurfacing is an innovative technique that deeply penetrates the skin by laser radiation. The laser initiates the natural regeneration process by removing the outermost layer of damaged skin cells and promoting the production of collagen. As a result, the skin looks smoother, firmer and more youthful. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Hydration","text":"Delivered by certified specialists with years of experience."},{"title":"Fine Lines & Wrinkles","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Hyperpigmentation","text":"Every treatment is tailored to your goals and your skin."},{"title":"Texture & Tone","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Laser Skin Resurfacing will I need?","a":"Typically 3-5 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30-60 minutes per session"},{"label":"Sessions","value":"3-5 sessions with intervals "},{"label":"Results","value":"lasting up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#a98a6d","#2a2420"],
  },
  {
    slug: "ipl-phototherapy",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "IPL Phototherapy",
    tagline: "Ideal for treating acne, pigmentation and skin rejuvenation.",
    metaTitle: "IPL Phototherapy in London (Islington) | K Clinics",
    metaDescription: "Are you looking for a way to improve skin texture, reduce pigmentation spots or treat acne? IPL Phototherapy (Intense Pulsed Light) is an innovative and ef",
    keywords: ["IPL Phototherapy London","IPL Phototherapy Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "Are you looking for a way to improve skin texture, reduce pigmentation spots or treat acne? IPL Phototherapy (Intense Pulsed Light) is an innovative and effective technique created to address all these issues. Short, powerful light bursts focus on trouble spots, such as redness, pigmentation or damaged blood vessels to treat them. This procedure activates the skin's natural regeneration, so leaving it smoother, more even-toned and healthier. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Hyperpigmentation","text":"Delivered by certified specialists with years of experience."},{"title":"Fine Lines & Wrinkles","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Blemishes & Acne","text":"Every treatment is tailored to your goals and your skin."},{"title":"Redness & Vascular Issues","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of IPL Phototherapy will I need?","a":"Typically 4-6 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"20-40 minutes per session"},{"label":"Sessions","value":"4-6 sessions with intervals "},{"label":"Results","value":"Up to 8-12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#dcc4a8","#a98a6d"],
  },
  {
    slug: "fungal-nail-infection-treatment",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Fungal Nail Infection Treatment",
    tagline: "Ideal for effective and safe treatment of fungal nail infections.",
    metaTitle: "Fungal Nail Infection Treatment in London (Islington) | K Clinics",
    metaDescription: "Laser Fungal Nail Infection Treatment is a contemporary technique that safely and successfully gets rid of fungal nail infections without the use of chemic",
    keywords: ["Fungal Nail Infection Treatment London","Fungal Nail Infection Treatment Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "Laser Fungal Nail Infection Treatment is a contemporary technique that safely and successfully gets rid of fungal nail infections without the use of chemical medications. The laser beam eliminates the fungal infection at the cellular level, by penetrating the nail's deep layers.",
    benefits: [{"title":"Effective Elimination of Fungus","text":"Delivered by certified specialists with years of experience."},{"title":"Improved Nail Appearance","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Fungal Nail Infection Treatment will I need?","a":"Typically 4-8 treatments with interval. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"20-30 minutes"},{"label":"Sessions","value":"4-8 treatments with interval"},{"label":"Results","value":"Improvement after each sessi"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#7b6a5d","#4a3f37"],
  },
  {
    slug: "permanent-makeup-removal",
    category: "aesthetics",
    group: "Laser & Skin",
    title: "Permanent MakeUp Removal",
    tagline: "Ideal for removing old, unwanted permanent makeup from eyebrows.",
    metaTitle: "Permanent MakeUp Removal in London (Islington) | K Clinics",
    metaDescription: "Are you looking for a painless and scar-free way to remove undesirable permanent makeup? Permanent Makeup Removal is a modern and safe method designed to e",
    keywords: ["Permanent MakeUp Removal London","Permanent MakeUp Removal Islington","aesthetic clinic London"],
    eyebrow: "Laser & Skin",
    intro: "Are you looking for a painless and scar-free way to remove undesirable permanent makeup? Permanent Makeup Removal is a modern and safe method designed to effectively eliminate pigment from the skin. Due to laser technology the pigment is broken down into small particles, which the body then naturally gets rid of. After the procedure, the skin becomes lighter and the undesired makeup gradually disappears, giving the look of natural skin. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Reduction in Scars","text":"Delivered by certified specialists with years of experience."},{"title":"Tone & Texture","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Skin Sensitivity","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Permanent MakeUp Removal will I need?","a":"Typically 3-6 treatments with interval. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30-60 minutes"},{"label":"Sessions","value":"3-6 treatments with interval"},{"label":"Results","value":"2-4 weeks after each session"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#c2a589","#2a2420"],
  },
  {
    slug: "microneedling",
    category: "aesthetics",
    group: "Face & Lifting",
    title: "Microneedling",
    tagline: "Ideal for treating acne, stretch marks, scars and skin rejuvenation.",
    metaTitle: "Microneedling in London (Islington) | K Clinics",
    metaDescription: "Looking to make your skin smoother, reduce stretch marks or eliminate scars? Your skin's natural regeneration process is triggered by the easy and efficien",
    keywords: ["Microneedling London","Microneedling Islington","aesthetic clinic London"],
    eyebrow: "Face & Lifting",
    intro: "Looking to make your skin smoother, reduce stretch marks or eliminate scars? Your skin's natural regeneration process is triggered by the easy and efficient microneedling treatment. During the procedure, tiny, sterile needles make tiny holes in the skin's surface, which promotes the formation of collagen and elastin and starts the healing process. Without requiring a long recuperation time, this leaves your skin feeling firmer, fresher and more rejuvenated. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Hydration","text":"Delivered by certified specialists with years of experience."},{"title":"Fine Lines & Wrinkles","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Hyperpigmentation","text":"Every treatment is tailored to your goals and your skin."},{"title":"Texture & Tone","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Microneedling will I need?","a":"Typically 4-6 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30-60 minutes per session"},{"label":"Sessions","value":"4-6 sessions with intervals "},{"label":"Results","value":"Up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#a98a6d","#7b6a5d"],
  },
  {
    slug: "prp-therapy",
    category: "aesthetics",
    group: "Face & Lifting",
    title: "PRP Therapy",
    tagline: "Ideal for skin rejuvenation, acne treatment, stretch marks and scars.",
    metaTitle: "PRP Therapy in London (Islington) | K Clinics",
    metaDescription: "Looking for a natural way to rejuvenate your skin, reduce scars or diminish stretch marks? PRP Therapy (Platelet-Rich Plasma Therapy) is a successful and e",
    keywords: ["PRP Therapy London","PRP Therapy Islington","aesthetic clinic London"],
    eyebrow: "Face & Lifting",
    intro: "Looking for a natural way to rejuvenate your skin, reduce scars or diminish stretch marks? PRP Therapy (Platelet-Rich Plasma Therapy) is a successful and effective treatment that restores skin health by utilising your body's natural resources. Throughout the procedure, platelet-rich plasma is drawn from your blood and injected into problem areas. This plasma enhances blood circulation, speeds up tissue repair, encourages the creation of collagen and elastin, and stimulates natural regeneration processes. The result is firmer, more luminous and regenerated skin without a long recovery period. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Skin Regeneration","text":"Delivered by certified specialists with years of experience."},{"title":"Skin Elasticity","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Reduction in Scars","text":"Every treatment is tailored to your goals and your skin."},{"title":"Fine Lines & Wrinkles","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of PRP Therapy will I need?","a":"Typically 3-6 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30-60 minutes per session"},{"label":"Sessions","value":"3-6 sessions with intervals "},{"label":"Results","value":"Up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#cdb4a3","#7b6a5d"],
  },
  {
    slug: "chemical-peels",
    category: "aesthetics",
    group: "Face & Lifting",
    title: "Chemical Peels",
    tagline: "Ideal for cleansing, skin rejuvenation, acne treatment and evening out skin tone.",
    metaTitle: "Chemical Peels in London (Islington) | K Clinics",
    metaDescription: "Looking for a way to cleanse your skin, get rid of acne or even out your skin tone? Cosmetic peels are an innovative procedure for skin rejuvenation and th",
    keywords: ["Chemical Peels London","Chemical Peels Islington","aesthetic clinic London"],
    eyebrow: "Face & Lifting",
    intro: "Looking for a way to cleanse your skin, get rid of acne or even out your skin tone? Cosmetic peels are an innovative procedure for skin rejuvenation and thorough cleaning. The top layer of dead cells is carefully removed from the skin throughout the treatment by using a specific solution. This promotes the skin's natural regeneration process, evens out the tone, enhances skin texture, and brings back the skin's brightness and freshness. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Tone & Texture","text":"Delivered by certified specialists with years of experience."},{"title":"Fine Lines & Wrinkles","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Hyperpigmentation","text":"Every treatment is tailored to your goals and your skin."},{"title":"Blemishes & Acne","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Chemical Peels will I need?","a":"Typically 3-6 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30 minutes"},{"label":"Sessions","value":"3-6 sessions with intervals "},{"label":"Results","value":"Up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#c2a589","#4a3f37"],
  },
  {
    slug: "microdermabrasion",
    category: "aesthetics",
    group: "Face & Lifting",
    title: "Microdermabrasion",
    tagline: "Ideal for cleansing, skin rejuvenation, acne treatment and texture improvement.",
    metaTitle: "Microdermabrasion in London (Islington) | K Clinics",
    metaDescription: "Looking to gently cleanse your skin, reduce acne and improve skin texture? Microdermabrasion is a contemporary technique for deep cleaning and skin renewal",
    keywords: ["Microdermabrasion London","Microdermabrasion Islington","aesthetic clinic London"],
    eyebrow: "Face & Lifting",
    intro: "Looking to gently cleanse your skin, reduce acne and improve skin texture? Microdermabrasion is a contemporary technique for deep cleaning and skin renewal. It eliminates the outermost layer of dead skin cells using a specialised tool with a diamond-tipped applicator or microcrystal. This procedure enhances skin texture, promotes natural regeneration and gives your skin a bright, healthy appearance. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Tone & Texture","text":"Delivered by certified specialists with years of experience."},{"title":"Hyperpigmentation","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Blemishes & Acne","text":"Every treatment is tailored to your goals and your skin."},{"title":"Reduction in Scars","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Microdermabrasion will I need?","a":"Typically 3-6 sessions with intervals . We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30 minutes"},{"label":"Sessions","value":"3-6 sessions with intervals "},{"label":"Results","value":"Up to 12 months"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#dcc4a8","#7b6a5d"],
  },
  {
    slug: "botox",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Botox",
    tagline: "Ideal for smooth out dynamic wrinkles, prevent their formation.",
    metaTitle: "Botox in London (Islington) | K Clinics",
    metaDescription: "Do you want to rejuvenate your face and get rid of wrinkles? Botox is a modern cosmetic method that smooths dynamic wrinkles, prevents their formation, and",
    keywords: ["Botox London","Botox Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Do you want to rejuvenate your face and get rid of wrinkles? Botox is a modern cosmetic method that smooths dynamic wrinkles, prevents their formation, and makes the face look younger and more harmonious. Botulinum toxin is injected into the muscles responsible for wrinkles, temporarily blocking their activity. As a result, the skin may relax and look fresh and natural without requiring a lengthy recovery time. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Fine Lines & Wrinkles","text":"Delivered by certified specialists with years of experience."},{"title":"Sweat Reduction","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Facial Contouring","text":"Every treatment is tailored to your goals and your skin."},{"title":"Anti-Ageing","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Botox will I need?","a":"Typically 1 treatment every 3-4 months. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"15-30 minutes"},{"label":"Sessions","value":"1 treatment every 3-4 months"},{"label":"Results","value":"2-5 days after the procedure"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#cdb4a3","#a98a6d"],
  },
  {
    slug: "dermal-fillers",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Dermal Fillers",
    tagline: "Ideal for restoring facial volume, contouring, reducing wrinkles and folds, adding volume and shape to lips.",
    metaTitle: "Dermal Fillers in London (Islington) | K Clinics",
    metaDescription: "Dermal Fillers are a modern cosmetic procedure designed to refresh the face, smooth wrinkles, enhance contours and address a wide range of aesthetic concer",
    keywords: ["Dermal Fillers London","Dermal Fillers Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Dermal Fillers are a modern cosmetic procedure designed to refresh the face, smooth wrinkles, enhance contours and address a wide range of aesthetic concerns. Fillers smooth the skin for a more youthful appearance by successfully correcting deep wrinkles such as marionette lines and nasolabial folds. Also they give the lips better volume and improve their definition, symmetry and general appearance. Additionally, dermal fillers provide a harmonious face contour by restoring lost volume due to aging in areas such as the cheeks, chin and temples. As a result the skin becomes more elastic and glowing due to moisture from hyaluronic acid. In addition to offering immediate results, fillers promote the synthesis of collagen, enhancing the general health of the skin and guaranteeing long-lasting results. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Facial Contouring","text":"Delivered by certified specialists with years of experience."},{"title":"Fine Lines & Wrinkles","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Hydration","text":"Every treatment is tailored to your goals and your skin."},{"title":"Texture & Tone","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Dermal Fillers will I need?","a":"Typically 1 treatment every 12-18 mont. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30-60 minutes"},{"label":"Sessions","value":"1 treatment every 12-18 mont"},{"label":"Results","value":"Immediately after the proced"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#c2a589","#7b6a5d"],
  },
  {
    slug: "kybella",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Kybella (Submental Fat Reduction)",
    tagline: "Ideal for reducing a double chin and improving the contours of the lower face.",
    metaTitle: "Kybella (Submental Fat Reduction) in London (Islington) | K Clinics",
    metaDescription: "Dreaming of getting rid of a double chin without surgery? Kybella is an innovative, successful technique for decreasing chin fat volume. Deoxycholic acid, ",
    keywords: ["Kybella (Submental Fat Reduction) London","Kybella (Submental Fat Reduction) Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Dreaming of getting rid of a double chin without surgery? Kybella is an innovative, successful technique for decreasing chin fat volume. Deoxycholic acid, the main component of the treatment, naturally breaks down fat cells. After the procedure, the skin looks tighter and facial features become more defined. This safe treatment requires no lengthy recovery and provides long-lasting results. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Facial Contouring","text":"Delivered by certified specialists with years of experience."},{"title":"Skin Tightening","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Kybella (Submental Fat Reduction) will I need?","a":"Typically 2-4 treatments with interval. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"15-30 minutes"},{"label":"Sessions","value":"2-4 treatments with interval"},{"label":"Results","value":"Noticeable within 4-6 weeks "}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#a98a6d","#2a2420"],
  },
  {
    slug: "anti-cellulite-programs",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Anti-Cellulite Programs",
    tagline: "Ideal for reducing cellulite and improving skin texture.",
    metaTitle: "Anti-Cellulite Programs in London (Islington) | K Clinics",
    metaDescription: "Dreaming of smooth skin and freedom from cellulite? Anti-Cellulite Programs are designed to effectively reduce skin irregularities, stimulate blood circula",
    keywords: ["Anti-Cellulite Programs London","Anti-Cellulite Programs Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Dreaming of smooth skin and freedom from cellulite? Anti-Cellulite Programs are designed to effectively reduce skin irregularities, stimulate blood circulation, and restore natural elasticity. By employing sophisticated methods, these treatments focus on the skin's deeper layers, encouraging the elimination of extra fluid, enhancing lymphatic drainage and stimulating collagen creation.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Anti-Cellulite Programs will I need?","a":"Typically 6-12 treatments with interva. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30-90 minutes per session"},{"label":"Sessions","value":"6-12 treatments with interva"},{"label":"Results","value":"After the first session"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#a98a6d","#4a3f37"],
  },
  {
    slug: "vacuum-massage",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Vacuum Massage",
    tagline: "Ideal for reducing cellulite and improving skin texture.",
    metaTitle: "Vacuum Massage in London (Islington) | K Clinics",
    metaDescription: "Vacuum massage is a modern technique aimed at combating cellulite, improving blood circulation and lymphatic drainage and restoring skin tone. Negative pre",
    keywords: ["Vacuum Massage London","Vacuum Massage Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Vacuum massage is a modern technique aimed at combating cellulite, improving blood circulation and lymphatic drainage and restoring skin tone. Negative pressure is produced using a specialized vacuum device to activate deep tissue layers, which aids in the removal of extra fluid and toxins.",
    benefits: [{"title":"Cellulite Reduction","text":"Delivered by certified specialists with years of experience."},{"title":"Improved Circulation","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Lymphatic Drainage","text":"Every treatment is tailored to your goals and your skin."},{"title":"Skin Tightening","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Vacuum Massage will I need?","a":"Typically 6-12 treatments with interva. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"40-60 minutes"},{"label":"Sessions","value":"6-12 treatments with interva"},{"label":"Results","value":"After completing the full co"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#dcc4a8","#7b6a5d"],
  },
  {
    slug: "hip-dip-filler",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Hip Dip Filler",
    tagline: "Ideal for correcting hip contours and creating a harmonious silhouette.",
    metaTitle: "Hip Dip Filler in London (Islington) | K Clinics",
    metaDescription: "Hip Dip Filler is a modern, non-invasive procedure aimed at smoothing hip contours and eliminating irregularities in the dip area. This procedure creates s",
    keywords: ["Hip Dip Filler London","Hip Dip Filler Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Hip Dip Filler is a modern, non-invasive procedure aimed at smoothing hip contours and eliminating irregularities in the dip area. This procedure creates smooth lines and a balanced look by special filler, which adds volume where it is needed. When injected beneath the skin, the fillers improve tissue elasticity, promote collagen synthesis and provide a result that looks natural. As a result, the form becomes appealing and proportional and the hip outlines seem more symmetrical. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Body Contouring","text":"Delivered by certified specialists with years of experience."},{"title":"Tighter Skin","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Hip Dip Filler will I need?","a":"Typically 1-3 treatments with interval. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"40-60 minutes"},{"label":"Sessions","value":"1-3 treatments with interval"},{"label":"Results","value":"after the first session"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#cdb4a3","#4a3f37"],
  },
  {
    slug: "body-hifu-lifting",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Body SMAS (HIFU) Lifting",
    tagline: "Ideal for tightening and improving body contours.",
    metaTitle: "Body SMAS (HIFU) Lifting in London (Islington) | K Clinics",
    metaDescription: "Body SMAS (HIFU) Lifting is a modern, non-invasive technology designed to tighten the skin, improve body contours, and restore firmness. The process target",
    keywords: ["Body SMAS (HIFU) Lifting London","Body SMAS (HIFU) Lifting Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Body SMAS (HIFU) Lifting is a modern, non-invasive technology designed to tighten the skin, improve body contours, and restore firmness. The process targets the deep tissue layers that give skin its flexibility and tone, including the superficial layers of the dermis (1.5–3 mm) and the SMAS layer (about 4.5 mm).",
    benefits: [{"title":"Body Contouring","text":"Delivered by certified specialists with years of experience."},{"title":"Body Lifting","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Skin Tightening","text":"Every treatment is tailored to your goals and your skin."},{"title":"Cellulite Reduction","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Body SMAS (HIFU) Lifting will I need?","a":"Typically 3-6 treatments with interval. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"40-90 minutes"},{"label":"Sessions","value":"3-6 treatments with interval"},{"label":"Results","value":"Noticeable effect after the "}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#7b6a5d","#2a2420"],
  },
  {
    slug: "intimate-area-whitening",
    category: "aesthetics",
    group: "Body & Injectables",
    title: "Intimate Area Whitening",
    tagline: "Ideal for evening out the skin tone in the intimate area.",
    metaTitle: "Intimate Area Whitening in London (Islington) | K Clinics",
    metaDescription: "Intimate area whitening is a modern, safe, and effective procedure aimed at reducing excessive pigmentation and evening out the skin tone. Dark spots are e",
    keywords: ["Intimate Area Whitening London","Intimate Area Whitening Islington","aesthetic clinic London"],
    eyebrow: "Body & Injectables",
    intro: "Intimate area whitening is a modern, safe, and effective procedure aimed at reducing excessive pigmentation and evening out the skin tone. Dark spots are eliminated and the skin's natural regeneration processes are triggered with CO2 laser technology. As a result the skin gets softer, smoother and more attractive. This process offers a rapid and painless means of achieving the desired outcomes, improving appearance and increasing self-assurance. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Intimate Rejuvenation","text":"Delivered by certified specialists with years of experience."},{"title":"Hyperpigmentation","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Tone & Texture","text":"Every treatment is tailored to your goals and your skin."},{"title":"Skin Sensitivity","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Intimate Area Whitening will I need?","a":"Typically 3-6 treatments with interval. We confirm your exact plan at a complimentary consultation."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Duration","value":"30-60 minutes"},{"label":"Sessions","value":"3-6 treatments with interval"},{"label":"Results","value":"Noticeable effect after the "}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#cdb4a3","#2a2420"],
  },
  {
    slug: "cavity-treatment-and-fillings",
    category: "dentistry",
    group: "General Dentistry",
    title: "Cavity treatment and fillings",
    tagline: "Treat cavities early and keep your teeth healthy with our professional filling services.",
    metaTitle: "Cavity treatment and fillings in London (Islington) | K Clinics",
    metaDescription: "Timely tooth fillings are a key step in preserving oral health and the aesthetics of your smile. Early cavity detection makes treatment simple and preserve",
    keywords: ["Cavity treatment and fillings London","Cavity treatment and fillings Islington","dentist London"],
    eyebrow: "General Dentistry",
    intro: "Timely tooth fillings are a key step in preserving oral health and the aesthetics of your smile. Early cavity detection makes treatment simple and preserves the majority of the tooth's natural structure. If fillings are neglected or put off, an infection may progress further into the tooth, causing discomfort and then you need more involved and expensive procedures like root canals. Fillings not only stop decay, but also restore the tooth's natural function and appearance, avoiding more issues and boosting your comfort level with your smile. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Cavity treatment and fillings will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#dcc4a8","#7b6a5d"],
  },
  {
    slug: "professional-teeth-cleaning",
    category: "dentistry",
    group: "General Dentistry",
    title: "Professional teeth cleaning",
    tagline: "Our professional teeth cleaning keeps your gums healthy and your teeth shining bright.",
    metaTitle: "Professional teeth cleaning in London (Islington) | K Clinics",
    metaDescription: "A radiant smile and general oral health depend on your clean, healthy teeth. To prevent gum disease, cavities and other oral problems, which can result fro",
    keywords: ["Professional teeth cleaning London","Professional teeth cleaning Islington","dentist London"],
    eyebrow: "General Dentistry",
    intro: "A radiant smile and general oral health depend on your clean, healthy teeth. To prevent gum disease, cavities and other oral problems, which can result from plaque and tartar accumulation, we advise you to do Professional Dental Hygiene, even if you have good at-home care. These difficult-to-reach deposits can be removed with Professional Teeth Cleansing service and as a result your teeth feel clean, shiny and healthy. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Professional teeth cleaning will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#e3d3c4","#a98a6d"],
  },
  {
    slug: "root-canal-treatment",
    category: "dentistry",
    group: "General Dentistry",
    title: "Endodontics - Root canal treatment",
    tagline: "We at KClinics know how important it is to keep your natural teeth in order to preserve your oral health. So our special",
    metaTitle: "Endodontics - Root canal treatment in London (Islington) | K Clinics",
    metaDescription: "We at KClinics know how important it is to keep your natural teeth in order to preserve your oral health. So our specialists in endodontic therapies can he",
    keywords: ["Endodontics - Root canal treatment London","Endodontics - Root canal treatment Islington","dentist London"],
    eyebrow: "General Dentistry",
    intro: "We at KClinics know how important it is to keep your natural teeth in order to preserve your oral health. So our specialists in endodontic therapies can help you avoid teeth extracted by successfully treating dental infections or damages. We guarantee you reliable and painless root canal therapy without discomfort and maintain your natural smile.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Endodontics - Root canal treatment will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#a98a6d","#2a2420"],
  },
  {
    slug: "tooth-extraction",
    category: "dentistry",
    group: "General Dentistry",
    title: "Tooth extraction",
    tagline: "We remove problematic teeth with precision, helping you maintain overall oral health.",
    metaTitle: "Tooth extraction in London (Islington) | K Clinics",
    metaDescription: "Poor dental condition can lead to serious health problems, including infections, pain and impaired oral function. And sometimes these damages or other dent",
    keywords: ["Tooth extraction London","Tooth extraction Islington","dentist London"],
    eyebrow: "General Dentistry",
    intro: "Poor dental condition can lead to serious health problems, including infections, pain and impaired oral function. And sometimes these damages or other dental issues make it impossible to save a tooth and extraction is the only way to guarantee your comfort and long-term well-being. Using innovative tools and techniques, our dentists execute tooth extraction treatments with the highest care and accuracy to guarantee a comfortable and painless experience throughout all time. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Tooth extraction will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#7b6a5d","#4a3f37"],
  },
  {
    slug: "dental-crowns",
    category: "dentistry",
    group: "Restorative & Specialist",
    title: "Crown fabrication and placement",
    tagline: "From precise fabrication to comfortable placement, our crowns are designed to look and feel just like your natural teeth",
    metaTitle: "Crown fabrication and placement in London (Islington) | K Clinics",
    metaDescription: "At KClinics, we provide complete crown manufacturing and placement procedures to restore your smile's natural beauty in addition to its functionality. Our ",
    keywords: ["Crown fabrication and placement London","Crown fabrication and placement Islington","dentist London"],
    eyebrow: "Restorative & Specialist",
    intro: "At KClinics, we provide complete crown manufacturing and placement procedures to restore your smile's natural beauty in addition to its functionality. Our team uses innovative methods and premium products to guarantee long-lasting effects and make every patient feel comfortable. In order to ensure your confidence in the final, we strive to make the process as easy, educational and efficient as possible. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Crown fabrication and placement will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#dcc4a8","#7b6a5d"],
  },
  {
    slug: "dental-bridges",
    category: "dentistry",
    group: "Restorative & Specialist",
    title: "Bridge Fabrication and Placement",
    tagline: "Replace missing teeth with expertly designed bridges that blend perfectly with your natural teeth.",
    metaTitle: "Bridge Fabrication and Placement in London (Islington) | K Clinics",
    metaDescription: "One of the best and most tried-and-true techniques for repairing the dental arch is a bridge prosthetic, which enables the replacement of lost teeth and th",
    keywords: ["Bridge Fabrication and Placement London","Bridge Fabrication and Placement Islington","dentist London"],
    eyebrow: "Restorative & Specialist",
    intro: "One of the best and most tried-and-true techniques for repairing the dental arch is a bridge prosthetic, which enables the replacement of lost teeth and the return of normal oral function. Losing teeth can interfere with speaking, chewing, and even self-confidence. Because we at KClinics recognize the value of a beautiful and healthy smile, we provide first-class services for the manufacture and placement of bridges using premium materials and innovative technology to guarantee longevity and a natural appearance. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Bridge Fabrication and Placement will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#c2a589","#4a3f37"],
  },
  {
    slug: "braces",
    category: "dentistry",
    group: "Orthodontics",
    title: "Braces",
    tagline: "With our braces, enjoy a journey to straighter teeth and enhanced oral health.",
    metaTitle: "Braces in London (Islington) | K Clinics",
    metaDescription: "Having straight teeth doesn’t only benefit your self-confidence; it helps to improve your overall oral health and teeth function, and make your teeth and g",
    keywords: ["Braces London","Braces Islington","dentist London"],
    eyebrow: "Orthodontics",
    intro: "Having straight teeth doesn’t only benefit your self-confidence; it helps to improve your overall oral health and teeth function, and make your teeth and gum health easier to maintain. An orthodontic system also called braces is used to straighten teeth and adjust the alignment of the bite. They are a crucial part of contemporary dentistry since they aid in the treatment of numerous functional and cosmetic problems pertaining to bite and tooth alignment. A braces system consists of small brackets that are attached to each tooth and an archwire, a unique metal or ceramic wire, connects the brackets to produce regulated tension that progressively shifts the teeth into their proper positions. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Braces will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#e3d3c4","#7b6a5d"],
  },
  {
    slug: "clear-braces",
    category: "dentistry",
    group: "Orthodontics",
    title: "Ceramic/Clear Braces",
    tagline: "Ceramic or clear braces are a popular and aesthetic choice for orthodontic treatment, especially for patients who prefer",
    metaTitle: "Ceramic/Clear Braces in London (Islington) | K Clinics",
    metaDescription: "Ceramic or clear braces are a popular and aesthetic choice for orthodontic treatment, especially for patients who prefer a more discreet option. Compared t",
    keywords: ["Ceramic/Clear Braces London","Ceramic/Clear Braces Islington","dentist London"],
    eyebrow: "Orthodontics",
    intro: "Ceramic or clear braces are a popular and aesthetic choice for orthodontic treatment, especially for patients who prefer a more discreet option. Compared to conventional metal braces, these braces are far less apparent since they are composed of premium ceramic materials that match teeth's natural colour. Like metal braces, ceramic braces straighten teeth and successfully treat bite problems but have a less noticeable appearance.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Ceramic/Clear Braces will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#dcc4a8","#a98a6d"],
  },
  {
    slug: "smile-enhancement",
    category: "dentistry",
    group: "Aesthetic Dentistry",
    title: "Smile enhancement",
    tagline: "Your smile is your signature - let us help make it unforgettable.",
    metaTitle: "Smile enhancement in London (Islington) | K Clinics",
    metaDescription: "Your smile is your style, confidence and personal signature. It impacts not only how others perceive you but also your oral health and overall comfort in l",
    keywords: ["Smile enhancement London","Smile enhancement Islington","dentist London"],
    eyebrow: "Aesthetic Dentistry",
    intro: "Your smile is your style, confidence and personal signature. It impacts not only how others perceive you but also your oral health and overall comfort in life. We understand that every smile is unique, and its enhancement should be an accessible procedure. To produce a smile that looks natural, harmonious and captures your unique personality at our clinic we combined modern dental technology, our specialists' skill and your preferences. We would be delighted to welcome you to our Islington clinic.",
    benefits: [{"title":"Expert clinicians","text":"Delivered by certified specialists with years of experience."},{"title":"Advanced technology","text":"The latest medical-grade equipment for safe, lasting results."},{"title":"Personalised plan","text":"Every treatment is tailored to your goals and your skin."},{"title":"Considered care","text":"A calm, private and welcoming clinic experience."}],
    process: [{"title":"Consultation","text":"A thorough, unhurried assessment of your goals and suitability."},{"title":"Your treatment","text":"Delivered with precision and care by an expert clinician."},{"title":"Results & aftercare","text":"Attentive aftercare and a plan to maintain your results."}],
    faqs: [{"q":"How many sessions of Smile enhancement will I need?","a":"We design a tailored plan at your complimentary consultation, based on your goals and skin."},{"q":"Is there any downtime?","a":"Most clients return to their day promptly. We share precise aftercare guidance for your treatment."},{"q":"How do I get started?","a":"Book online or request a complimentary consultation — there is never any obligation."}],
    facts: [{"label":"Consult","value":"Complimentary"},{"label":"Downtime","value":"Minimal"},{"label":"Setting","value":"Islington, London"}],
    priceFrom: "On consultation",
    related: [],
    gradient: ["#e3d3c4","#3d352f"],
  },
];
